import Head from 'next/head'
import ImageLink from '../components/ImageLink/ImageLink'

import coffee from '../../public/coffee.jpg'
import Tea from '../../public/tea.jpg'
import styles from '../../styles/Home.module.css'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>



        
      </main>

      <section className='SectionContainer'>
        <ImageLink link="/products/coffee" image={coffee} name='coffee' alt="coffee cup around a table" />
        <ImageLink link="/products/tea" image={Tea} name='Tea' alt="display of tea cups"/>
      </section>

      <section>

      </section>
    </>
  )
}

